#!/usr/bin/env bash

icons=("" "" "" "" "" "" "" "")
# macsmc-battery: see /sys/class/power_supply/
gettime() {
    FULL=$(cat /sys/class/power_supply/macsmc-battery/charge_full)
    NOW=$(cat /sys/class/power_supply/macsmc-battery/charge_now)

    if [ "$RATE" -gt 0 ]; then
        if [ "$STATE" = "Discharging" ]; then
            EX="$NOW / $RATE"
        else
            EX="($FULL - $NOW) / $RATE"
        fi
        date -u -d@"$(bc -l <<< "$EX * 3600")" +%H:%M
    fi
}

geticon() {
    echo "${icons[$level]}"
}

status() {
    echo -n "charging"
}

statch() {
    echo 'charging'
}

chargestatus() {
    echo -n ""
}

circolor() {
    cat images/svg/color.txt
}

cirbgcolor() {
    echo 'transparent'
}

color() {
    echo 'white'
}

bgcolor() {
    echo 'transparent'
}

wattage() {
    echo "$(bc -l <<< "scale=1; $RATE / 1000000") W"
}

warnedlow=0

while true; do
    RATE="127799000"
    CAPACITY="100"
    STATE="Full"

    warnedlow=0

    echo '{"quickicon": "'"$(chargestatus)"'", "icon": "'"$(geticon)"'", "percentage": '"$CAPACITY"', "wattage": "'"$(wattage)"'", "status": "'"$(status)"'", "circolor": "'"$(circolor)"'", "cirbgcolor": "'"$(cirbgcolor)"'", "color": "'"$(color)"'", "bgcolor": "'"$(bgcolor)"'" }'
    sleep 3
done
