require("core.options")
require("core.keymaps")
require("plugins-setup")
require("core.colorscheme")
-- plugins
require("plugins.nvim-cmp")
require("plugins.lsp") -- require the plugins.lsp.init
require("plugins.lualine")
require("plugins.telescope")
require("plugins.project")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.indentline")
require("plugins.which-key")
require("plugins.gitsigns")
require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.nvim-tree")
require("plugins.alpha")
require("plugins.symbols-outline") -- class outline
require("plugins.navic")
